Repository Icinga/icinga-go-library, pull requests merged in 2024-07, with the labels that each got.

#19 workflows: Fix `gosec` errors & enable code annotations
  .github/workflows/go.yml
  backoff/backoff.go
  config/config.go
  config/tls.go
  utils/utils.go
  version/version.go
Labels: cla/signed

#40 Make project name configurable
  version/version.go
Labels: cla/signed

#42 Enable dependabot
  .github/dependabot.yml
Labels: cla/signed

#37 com/: improve readability by removing redundant ifs
  com/atomic.go
  com/com.go
Labels: cla/signed

#31 types.*: assert interface compliance not stricter than needed
  types/binary.go
  types/bool.go
  types/unix_milli.go
  types/uuid.go
Labels: cla/signed

#25 Test UUID#Value()
  types/uuid_test.go
Labels: cla/signed, tests

#26 Test types.Int
  types/int_test.go
Labels: cla/signed, tests

#29 Test types.Binary
  types/binary_test.go
Labels: cla/signed, tests

#30 Test types.Bool
  types/bool_test.go
Labels: cla/signed, tests

#28 Test types.Name()
  types/utils_test.go
Labels: cla/signed, tests

#24 Test types.String
  types/string_test.go
Labels: cla/signed, tests

#48 logging: Sanitize Journald Field Key Names
  logging/journald_core.go
  logging/journald_core_test.go
Labels: bug, cla/signed
