Repository Icinga/icinga-go-library, pull requests merged in 2024-10, with the labels that each got.

#74 objectpacker: Assure gosec that in.Len() to uint64 cannot overflow
  objectpacker/objectpacker.go
Labels: cla/signed

#71 Test `config`
  config/config_test.go
  config/tls_test.go
Labels: cla/signed

#59 Actually retry every database error, including "pq: ..."
  retry/retry.go
Labels: cla/signed

#23 redis.Client#XReadUntilResult(): also re-try timeout errors
  redis/client.go
Labels: bug, cla/signed, ref/IP

#73 database: Document context limitations of Tx.Commit()
  database/db.go
Labels: cla/signed

#72 config/: enforce type constraints via generics, not reflection
  config/config.go
  config/contracts.go
Labels: cla/signed, enhancement

#79 Revert "Merge pull request #72 from Icinga/reflectPtr"
  config/config.go
  config/contracts.go
Labels: cla/signed

#75 Document `config`
  config/config.go
  config/contracts.go
  config/tls.go
Labels: cla/signed

#81 Also validate that arguments to `config` functions are struct pointers
  config/config.go
  config/config_test.go
Labels: cla/signed, enhancement

#53 db.DB/redis.Client: Details in Address for GetAddr
  database/db.go
  database/db_test.go
  redis/client.go
  redis/client_test.go
Labels: cla/signed, enhancement

#84 `logging#Config`: Fix `Options` can no longer be parsed by `go-yaml`
  logging/config.go
  logging/config_test.go
  testutils/testutils.go
Labels: cla/signed
